name: Code Quality

on:
  pull_request:
  push:
    branches: ["main"]

jobs:
  quality-check:
    name: Check Code Quality
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Node and Install Dependencies
        uses: ./.github/actions/setup-node-and-install-dependencies

      - name: Run oxlint
        run: pnpm lint

      - name: Check code formatting
        run: pnpm format:check

      - name: Run Typecheck
        run: pnpm typecheck

      - name: Build
        run: pnpm build
